# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6ae1df1605fa59ebdcff97b99935933"
name = "premium-translator"
handle = "premium-translator"
application_url = "https://connections-seo-motorcycle-valley.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1148b185.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://connections-seo-motorcycle-valley.trycloudflare.com/auth/callback",
  "https://connections-seo-motorcycle-valley.trycloudflare.com/auth/shopify/callback",
  "https://connections-seo-motorcycle-valley.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
